### ISSUE TITLE
base64 needs byte type

### ISSUE THREAD

**Issue by DvoryankinEvgeny** [theatlantic/python-hessian#5]
Hi. It looks like mistake at 
https://github.com/theatlantic/python-hessian/blob/7ec9def867c5026e98791fbed3b6b3f3eaeec210/pyhessian/client.py#L70
It should be something like
`auth = 'Basic ' + str(base64.b64encode(':'.join(credentials).encode('ASCII')))`

**Comment by SasoDeixDD** [comment]
I think, it should be like this 
`auth = 'Basic ' + base64.b64encode(':'.join(credentials).encode('ASCII')).decode('ASCII')`
Because `str` converts bytes to `b"string" `

**Comment by fdintino** [comment]
yes, this is a mistake. I'll push out an update later this week.

**Comment by sasodeixdd** [comment]
Could you, please, release a new version with this fix? Having it at pypi.org would be super convenient
